apiVersion: v1
kind: ConfigMap
metadata:
  name: claims-management-app-cm
data:
  artifactName: bpmn-poc.tar.gz
  artifactSha256: "chaning claims in qa"
  # command sha256sum bpmn-poc.tar.gz
  artifactUrl: "abcd.efgh"
