apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camunda-poc-sync
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/selflearner2025/argocd-job.git
    path: jobs
    
    targetRevision: camunda-sync
  destination:
    namespace: camunda
    name: in-cluster
  syncPolicy:
    automated:
      enable: true
     # prune: true
     # selfHeal: true
    syncOptions:
      - Replace=true
      #- ServerSideApply=false
