apiVersion: v1
kind: ConfigMap
metadata:
  name: cclaims-management-app-cm
data:
  artifactName: bpmn-poc.tar.gz
  artifactSha256: "hdjklslllss"
  # command sha256sum bpmn-poc.tar.gz
  artifactUrl: "abcd.efgh"
