apiVersion: v1
kind: ConfigMap
metadata:
  name: camunda-bpmn-artifact-repo-b
data:
  artifactName: bpmn-poc.tar.gz
  artifactSha256: "changing repo b"
  # command sha256sum bpmn-poc.tar.gz
  artifactUrl: "abcd.efgh"
