apiVersion: v1
kind: ConfigMap
metadata:
  name: violations-management-app-cm
data:
  artifactName: bpmn-poc.tar.gz
  artifactSha256: "change violations"
  # command sha256sum bpmn-poc.tar.gz
  artifactUrl: "abcd.efgh"
